### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [01org/hyperscan#1]
Some parameters (like "[${PROJECT_BINARY_DIR}/bin](https://github.com/01org/hyperscan/blob/904e436f11ed1197a1192b421ab7278975dce169/CMakeLists.txt#L39)" and "[${CMAKE_CURRENT_SOURCE_DIR}/autogen.py](https://github.com/01org/hyperscan/blob/904e436f11ed1197a1192b421ab7278975dce169/src/fdr/CMakeLists.txt#L13)") are passed to CMake commands in your build scripts without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like semicolons.

I would recommend to apply [advices from a wiki article](http://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes. "CMake splits arguments unless you use quotation marks or escapes.").

**Comment by mdb256** [comment]
Fixed in ba0b2b7
