### ISSUE TITLE
fails to link against gtest in shared mode

### ISSUE THREAD

**Issue by starius** [01org/hyperscan#19]
I build hyperscan in shared mode:

```
$ cmake ../hyperscan-4.1.0 -DBUILD_SHARED_LIBS=ON
$ make
```

It fails to build `bin/unit-hyperscan` because of linking errors:

```
allocators.cpp:41: undefined reference to `testing::Message::Message()'
allocators.cpp:41: undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
allocators.cpp:41: undefined reference to `testing::internal::AssertHelper::AssertHelper(testing::TestPartResult::Type, char const*, int, char const*)'
allocators.cpp:41: undefined reference to `testing::internal::AssertHelper::operator=(testing::Message const&) const'
allocators.cpp:41: undefined reference to `testing::internal::AssertHelper::~AssertHelper()'
... and so on
```

It is caused by the fact that symbols in libgtest.so are local:
```
$ nm --demangle lib/libgtest.so | grep IsTrue
000000000000a810 t testing::internal::IsTrue(bool)
```

It should be `T` instead of `t` there.

This problem seems to be caused by using `-fvisibility=hidden` compiler option when compiling `gtest`.

The following patch fixes the problem for me:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index b4d8175..b53fbdd 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -220,7 +220,7 @@ CHECK_FUNCTION_EXISTS(_aligned_malloc HAVE__ALIGNED_MALLOC)
 CHECK_C_COMPILER_FLAG(-fvisibility=hidden HAS_C_HIDDEN)
 CHECK_CXX_COMPILER_FLAG(-fvisibility=hidden HAS_CXX_HIDDEN)
 
-if (RELEASE_BUILD)
+if (RELEASE_BUILD AND NOT BUILD_STATIC_AND_SHARED AND NOT BUILD_SHARED_LIBS)
     if (HAS_C_HIDDEN)
         set(EXTRA_C_FLAGS "${EXTRA_C_FLAGS} -fvisibility=hidden")
     endif()
```

You may want to make more precise patch, which disables `-fvisibility=hidden` for `gtest` only, because other parts seem to work well with it.

**Comment by mdb256** [comment]
Thanks for this.

As it happens, we've already pushed commit https://github.com/01org/hyperscan/commit/3dc8bab78fecd9fc69a329c2359cab3288e11a00 that solves this issue in a different way, except it is still on the develop branch. We expect to merge this to master quite soon.

However we probably should rework our use of `-fvisibility=hidden` so that it is only applied to the Hyperscan shared libs.

**Comment by mdb256** [comment]
Commit 3dc8bab78fecd9fc69a329c2359cab3288e11a00 is now on master in release 4.2.0
