### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [01org/hyperscan#2]
Would you like to add more error handling for return values from functions like the following?
- [fopen](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fopen.html "Open a stream.") ⇒ [smwrDumpNFA](https://github.com/01org/hyperscan/blob/904e436f11ed1197a1192b421ab7278975dce169/src/smallwrite/smallwrite_dump.cpp#L65)
- [printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output.") ⇒ [dumpData](https://github.com/01org/hyperscan/blob/904e436f11ed1197a1192b421ab7278975dce169/src/runtime.c#L1451)

**Comment by mdb256** [comment]
This is in debug code for developers, not enabled in production builds.

Furthermore checking the return value of printf() does nothing except reduce the readability of the code.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.
Would you like to detect every error situation as early as possible (also for software debug builds)?
