### ISSUE TITLE
(?s), Dot-all and Extended syntax

### ISSUE THREAD

**Issue by starius** [01org/hyperscan#23]
The [Compilation part](http://01org.github.io/hyperscan/dev-reference/compilation.html#supported-constructs) of the tutorial provides two modifiers with the same value:

 * Dot-all: `(?s)` and `(?-s)`
 * Extended syntax: `(?s)` and `(?-s)`

This seems to be a typo.

Could you explain what is the difference between the modifiers Dot-all, Extended syntax and Multi-line and provide examples in the documentation, please?

**Comment by jviiret** [comment]
Quite right, this is indeed a typo. Extended syntax is controlled with `(?x)` and `(?-x)`, as per the PCRE syntax.

I'll get a fix with a bit more information into the developer guide shortly.

**Comment by jviiret** [comment]
Fixed in 428bb9a1 and d7466ff8, and I've updated the documentation on the Web for the 4.2.0 release.
