### ISSUE TITLE
(^|.) and ($|.) match empty string, but compilation doesn't fail with "Pattern matches empty buffer"

### ISSUE THREAD

**Issue by starius** [01org/hyperscan#25]

**Comment by jviiret** [comment]
You're quite right.

The ``HS_FLAG_ALLOWEMPTY`` flag and the "Pattern matches empty buffer" error are intended to prevent people from being surprised by Hyperscan's matching semantics when they use really trivial "match everywhere" patterns with maximizing quantifiers, like ``/.*/s`` -- you can think of them as a safety feature.

There are many ways to build more complex patterns that will match on the empty string and every byte, such as``/^|a|[^a]|$/``, but we don't currently provide an analysis that would warn on such cases.

**Comment by starius** [comment]
The detection of patterns matching the empty string can be done by scanning the pattern against the empty string.
