### ISSUE TITLE
build failed at OSX mavericks with Clang: 6.0 build 600

### ISSUE THREAD

**Issue by flier** [01org/hyperscan#27]
We I try to upgrade Hyperscan from v4.1.0 to [v4.2.0 for homebrew](https://github.com/Homebrew/homebrew-core/pull/2538), build failed at OSX mavericks with Clang: 6.0 build 600

```
/tmp/hyperscan-20160701-38604-nh3uxt/hyperscan-4.2.0/src/rose/rose_build_misc.cpp:883:16: error: chosen constructor is explicit in copy-initialization
        return {};
               ^~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/set:428:14: note: constructor declared here
    explicit set(const value_compare& __comp = value_compare())
             ^
```
Clang: 6.0 build 600
OS X: 10.9.5-x86_64
Xcode: 6.2
Please check the full build log at
http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/version=mavericks/4050/consoleFull

**Comment by jviiret** [comment]
Thanks for the report!

We had the same issue reported against some FreeBSD versions, and we already have the fix (the same one as in your PR) in testing internally. We will push it to the develop branch shortly, and it will be in the next release.

**Comment by flier** [comment]
Thanks

Justin Viiret <notifications@github.com>于2016年7月4日周一 12:38写道：

**Comment by mdb256** [comment]
We've pushed commit e9cfbae68 which fixes this issue. This is on the `develop` branch, and will be in the next release.

**Comment by flier** [comment]
Thanks, I need to wait your next release, because Homebrew refuse to use a develop revision instead of official release or tag :)

**Comment by mdb256** [comment]
v4.3.0 is out now and includes the commit.

**Comment by flier** [comment]
Got it, I have submitted [a new pull request](https://github.com/Homebrew/homebrew-core/pull/4203) to Homebrew for v4.3.0
