### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [01org/hyperscan#3]
Would you like to [replace any double quotes](https://github.com/01org/hyperscan/blob/904e436f11ed1197a1192b421ab7278975dce169/src/hs.h#L32 "Check header file inclusion style") by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by mdb256** [comment]
The double quotes in hs.h are correct. We want hs.h to include files in the same directory so we know the user ends up with headers from the same version of libhs.

While double quotes and angle brackets may have implementation-defined behaviours, this has the intended result on all of our supported compilers.

**Comment by elfring** [comment]
There are different opinions about the handling of the involved implementation-defined behaviour.
* Will header files be also searched outside the specified include directories if double quotes are used for the discussed preprocessor statement?
* Is there a speed difference measurable if a file is not found there and the search will be retried with "the angle brackets inclusion method"?
