### ISSUE TITLE
spurious executable permissions?

### ISSUE THREAD

**Issue by jmtaylor90** [01org/hyperscan#37]
In working on getting hyperscan packaged for Fedora/EPEL we came across the following rpmlint warnings:

hyperscan-debuginfo.x86_64: W: spurious-executable-perm /usr/src/debug/hyperscan-4.3.1/src/nfa/dfa_build_strat.cpp
hyperscan-debuginfo.x86_64: W: spurious-executable-perm /usr/src/debug/hyperscan-4.3.1/src/nfa/accel_dfa_build_strat.cpp
hyperscan-debuginfo.x86_64: W: spurious-executable-perm /usr/src/debug/hyperscan-4.3.1/src/nfa/accel_dfa_build_strat.h

The files above are indeed marked as executable (0775).

**Comment by mdb256** [comment]
They are indeed - how strange.

I'll merge your PR soon, and it will be part of the next release. That's probably not quite enough for us to create a 4.3.2 on its own, however.

**Comment by jmtaylor90** [comment]
Yeah, no problem at all. It was just something noted during the package review. Thanks for the quick response!

**Comment by mdb256** [comment]
Fixed in v4.4.0
