### ISSUE TITLE
Incorrect cmake version

### ISSUE THREAD

**Issue by eplanet** [01org/hyperscan#4]
The required version for cmake should be 2.8.11. The string(TIMESTAMP ...) directive was released in 2.8.11 but is not available in previous versions.

It could be nice to provide a workaround as well.

**Comment by mdb256** [comment]
Thanks for the bug report, fixed in ba0b2b7.

We decided to not add a workaround, as it is hard to do in a cross-platform manner, and 2.8.11 should be available on most recent distros.
