### ISSUE TITLE
In pcapscan example, maybe it not supports CRLF at the end of the line in windows mode

### ISSUE THREAD

**Issue by chenjuanpp** [01org/hyperscan#41]
I write some simple patterns in patterns.txt, error reported:
Pattern file: patterns.txt
'nsupported flag '
Thanks!

**Comment by mdb256** [comment]
Yes, the examples were not dealing with CR correctly - this had been fixed already but I hadn't pushed the fix, 83e69cc195b7677810bd7904561bb9e389baf514 is now in the develop branch for the next release.
