### ISSUE TITLE
Performance throughput questions

### ISSUE THREAD

**Issue by chenjuanpp** [01org/hyperscan#42]
Performance is not very ideal when I used over 5000 regular patterns testing on the Intel Xeon (R) (R) CPU E5-2667 v3 @ 3.20 GHz, open 16 threads test

SOM off    10.2 Gbps
SOM open 3.0 Gbps

Maybe my patterns are not well-written, Could you give some grammar specification or instructions in detail

**Comment by mdb256** [comment]
Are you able to describe the patterns you are using for this test? And how you are doing the benchmark?

Lower performance when looking for the start of match (SoM) is not surprising. The SoM information can be quite expensive to calculate, and affects performance and stream state size.

There is some information about writing patterns in our [developer reference guide](http://01org.github.io/hyperscan/dev-reference/performance.html).

**Comment by mdb256** [comment]
If you have any more questions, please open a new issue or get in touch directly.
