### ISSUE TITLE
build_wrapper.sh breaks on some directory names

### ISSUE THREAD

**Issue by stefan-baranoff** [01org/hyperscan#51]
Using version 4.4 building on CentOS 7.

When trying to build HyperScan in a sub-directory of certain paths such as "/home/our.business.com/someuser" the regex used with sed in cmake/build_wrapper.sh mangles paths.

Error from calling 'make':
`/home/business.example.com/someuser/regexengine/build/hyperscan-prefix/src/hyperscan/cmake/build_wrapper.sh: line 15: /opt/rh/devtoolset-6/root/usr/bin/ccom/someuser/regexengine/build/hyperscan-prefix/src/hyperscan-build: No such file or directory
CMakeFiles/hs_exec_shared_avx2.dir/build.make:62: recipe for target 'CMakeFiles/hs_exec_shared_avx2.dir/src/crc32.c.o' failed`

Output from build_wrapper.sh modified to print pre-sed and post-sed strings:
Before sed:

`/opt/rh/devtoolset-6/root/usr/bin/cc -I/home/business.example.com/someuser/regexengine/build/hyperscan-prefix/src/hyperscan-build -I/home/business.example.com/someuser/regexengine/build/hyperscan-prefix/src/hyperscan -I/home/business.example.com/someuser/regexengine/build/hyperscan-prefix/src/hyperscan/src -isystem /home/business.example.com/someuser/regexengine/build/hyperscan-prefix/src/hyperscan/include -isystem /usr/local/include -O3 -std=c99 -Wall -Wextra -Wshadow -Wcast-qual -fno-strict-aliasing -DNDEBUG -Wno-array-bounds -Wno-maybe-uninitialized -fno-omit-frame-pointer -Wno-abi -fvisibility=hidden -Wvla -Wpointer-arith -Wstrict-prototypes -Wmissing-prototypes -g -DNDEBUG -fPIC -march=core2 -o CMakeFiles/hs_exec_shared_core2.dir/src/crc32.c.o -c /home/business.example.com/someuser/regexengine/build/hyperscan-prefix/src/hyperscan/src/crc32.c`

After sed:

`/opt/rh/devtoolset-6/root/usr/bin/ccom/someuser/regexengine/build/hyperscan-prefix/src/hyperscan-build -I/home/business.example.com/someuser/regexengine/build/hyperscan-prefix/src/hyperscan -I/home/business.example.com/someuser/regexengine/build/hyperscan-prefix/src/hyperscan/src -isystem /home/business.example.com/someuser/regexengine/build/hyperscan-prefix/src/hyperscan/include -isystem /usr/local/include -O3 -std=c99 -Wall -Wextra -Wshadow -Wcast-qual -fno-strict-aliasing -DNDEBUG -Wno-array-bounds -Wno-maybe-uninitialized -fno-omit-frame-pointer -Wno-abi -fvisibility=hidden -Wvla -Wpointer-arith -Wstrict-prototypes -Wmissing-prototypes -g -DNDEBUG -fPIC -march=core2/home/business.example.com/someuser/regexengine/build/hyperscan-prefix/src/hyperscan/src/crc32.c`

**Comment by mdb256** [comment]
Thanks for reporting this, that is indeed a problem in the `sed` script.

I have a fix simplifying the script, and will put it through our test systems. A workaround is to build Hyperscan without the fat runtime, by passing `-DFAT_RUNTIME=off` to the CMake configuration stage.
