### ISSUE TITLE
build error on sqlite-3.6.20

### ISSUE THREAD

**Issue by leeyiw** [01org/hyperscan#52]
I was building hyperscan with sqlite-3.6.20 and got a compile error:

```
[ 98%] Building CXX object tools/hsbench/CMakeFiles/hsbench.dir/data_corpus.cpp.o
/home/yiwei.liyw/hyperscan-4.4.1/tools/hsbench/data_corpus.cpp: In function ‘std::vector<DataBlock> readCorpus(const string&)’:
/home/yiwei.liyw/hyperscan-4.4.1/tools/hsbench/data_corpus.cpp:113:37: error: ‘sqlite3_errstr’ was not declared in this scope
             << sqlite3_errstr(status);
                                     ^
make[2]: *** [tools/hsbench/CMakeFiles/hsbench.dir/data_corpus.cpp.o] Error 1
make[1]: *** [tools/hsbench/CMakeFiles/hsbench.dir/all] Error 2
make: *** [all] Error 2
```

Then I look into the `sqlite.h` and find there is no declaration of `sqlite3_errstr`, and this function declaration is exists on the latest version of sqlite3(sqlite3-3.18.0). So maybe add a dependency to SQLite, **which is missing in [current document](http://01org.github.io/hyperscan/dev-reference/getting_started.html#very-quick-start).** Or just don't use this function.

**Comment by mdb256** [comment]
This was fixed by e58a33c9cbdcccae3940137ff63bde734939b76d
