### ISSUE TITLE
hyperscan compile error with `no such instruction` error message

### ISSUE THREAD

**Issue by leeyiw** [01org/hyperscan#53]
I'm compiling hyperscan on CentOS 6.2, and compie error with following message:

```
/tmp/ccnZ8IHz.s: Assembler messages:
/tmp/ccnZ8IHz.s:671: Error: no such instruction: `vpbroadcastb %xmm3,%xmm3'
/tmp/ccnZ8IHz.s:680: Error: no such instruction: `vpbroadcastb %xmm2,%xmm2'
/tmp/ccnZ8IHz.s:855: Error: no such instruction: `vpbroadcastb %xmm3,%xmm3'
/tmp/ccnZ8IHz.s:864: Error: no such instruction: `vpbroadcastb %xmm2,%xmm2'
/tmp/ccnZ8IHz.s:1060: Error: no such instruction: `vpbroadcastb %xmm1,%xmm1'
/tmp/ccnZ8IHz.s:1178: Error: no such instruction: `vpbroadcastb %xmm1,%xmm1'
/tmp/ccnZ8IHz.s:1954: Error: no such instruction: `shlx %r8,%rax,%rax'
/tmp/ccnZ8IHz.s:2047: Error: no such instruction: `shlx %rdx,%rbx,%rdx'
/tmp/ccnZ8IHz.s:2055: Error: no such instruction: `shrx %r9d,%edx,%eax'
........
........
make[5]: *** [CMakeFiles/hs_exec_avx2.dir/src/runtime.c.o] Error 1
make[4]: *** [CMakeFiles/hs_exec_avx2.dir/all] Error 2
make[3]: *** [all] Error 2
```

I'm not sure this error is like #44 , But there is no fix or walk around in that issue. So I create new issue here.

My GCC version is: `gcc version 5.2.0 (GCC)`, as version is: `$as -v
GNU assembler version 2.20.51.0.2 (x86_64-redhat-linux) using BFD version version 2.20.51.0.2-5.28.2.alios6 20091009`

**Comment by mdb256** [comment]
The issue appears the same as #44 in that the assembler predates the AVX2 instruction set - it does not know how to assemble those instructions. 2009 was a long time ago.

We have been able to build Hyperscan on Centos 6 using the [devtoolset collections](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-4/), which include a newer GCC as well as bintutils that provides a more recent `as`.

If you are unable to upgrade the binutils package that provides `/bin/as`, a work around is to disable the fat runtime, which should means it won't attempt to compile AVX2 instructions.

We will look at updating the CMake configuration steps to catch this form of build error at an earlier stage.

**Comment by leeyiw** [comment]
@mdb256 That's great. After update my `as`, the build is success. Maybe you could add this issue to some FAQ or add version dependency at [Requirements](http://01org.github.io/hyperscan/dev-reference/getting_started.html#requirements)

**Comment by mdb256** [comment]
Very good. I'll close this issue now, so if there is anything else, please open a new one.

**Comment by Allen-kevin** [comment]
I had success installed hyperscan, but when i run command,
 gcc -o simplegrep simplegrep.c $(pkg-config --cflags --libs libhs)
 i got a error with following messages：
`simplegrep.c:61:16: fatal error: hs.h: No such file or directory
#include <hs.h>
compilation terminated.`

**Comment by xiangwang1** [comment]
Hi, what's your output of `pkg-config --cflags --libs libhs` in command line? 
Does it look like `-I/usr/local/include/hs -L/usr/local/lib -lhs`? If so, all required header files including `hs.h` should appear at `/usr/local/include/hs/`.

**Comment by Allen-kevin** [comment]
thank you!
