### ISSUE TITLE
Question about pcapscan

### ISSUE THREAD

**Issue by danielseol** [01org/hyperscan#59]
Hello.
I have a question about pcapscan bin.
Whenever trying to execute the pcapscan, the network signature of request packet can't be found in HTTP.
But, I can find the network signature of response packet in HTTP. Did I have a mistake to use this?

**Comment by jviiret** [comment]
Hi @danielseol,

The `pcapscan` example code is designed to be a demo for Hyperscan, and as such it only uses the network headers to associate packets in "streams" (note: not the same as doing any real flow reassembly, etc), then allows you to scan for patterns in the packet payload.

If you want to scan headers (is this what you mean by "network signature"?) then you will need to modify the code to scan them as well.

**Comment by danielseol** [comment]
Hi @jviiret 

Oh Thanks. jviiret.

I understand.
My request packet of HTTP is on HTTP/TCP/802.1Q Virtual Lan/Ethernet.
That's because "static bool payloadOffset" function doesn't care about this network layers.
So, it returns false (if iph->ip_v != 4, return false).

Have a nice day.

Daniel
Best Regards.
