### ISSUE TITLE
Concurrent call to hs_alloc_scratch() on the same database

### ISSUE THREAD

**Issue by sdeber** [01org/hyperscan#61]
Can I call hs_alloc_scratch() on the same database in multiple threads to allocation thread local scratch space concurrently without guarding the function call by a mutex? 

I am using version 4.5.1. In my current code, this is what I have done already. However, from time to time, some of the threads fails to search the database with error in validScratch(). Sometimes it gave error "bad magic 0x901343" , and sometimes it failed with the error "bad state size". 

Is it possible that this problem was caused by the fact that I am allocating scratch space instances concurrently?

**Comment by mdb256** [comment]
It is safe to call hs_alloc_scratch() in multiple threads using the same database.

Assuming the calls to hs_alloc_scratch() are successful, and that each thread calling hs_scan() has its own scratch, concurrent use should cause no problems.

Those cases from validScratch() do appear to be the result of using a pointer that isn't pointing a scratch region. Are you able to track the lifetime of those pointers (I'm a fan of printf() debugging), or maybe test using Valgrind?

As an aside: where possible we would usually recommend calling hs_alloc_scratch() once and then use hs_clone_scratch() to make copies of it, as cloning an existing scratch takes less work than allocating and initialising a new scratch, but this is just a performance change and there should be no difference in the end result.

**Comment by sdeber** [comment]
The issue was caused by user code, not by Hyperscan. So I am closing it off
