### ISSUE TITLE
deadloop in func roseRunProgram_i

### ISSUE THREAD

**Issue by landataosong** [01org/hyperscan#65]
Hi
  In my current test with hyperscan 4.5.1 release, sometimes, it will deadloop in function roseRunProgram_i. debug with gdb, I found the value of code in "switch ((enum RoseInstructionCode)code)"  is not in the range [ROSE_INSTR_END, LAST_ROSE_INSTRUCTION], and the func roseRunProgram_i has no default case, so it will deadloop by for (;;) { ............}, as the code's value has not changed.
  Any one could give me a method to avoid it(not fix it in hyperscan) as soon as possible, Thanks! Thanks!
  I found from https://01.org/zh/hyperscan ,
XIANG WANG
username: xiangwa1
Job Title: Software Engineer
Country: China
 
 Could anyone give me his mailbox, or please give me a mail to songtao.tian@gmail.com, we talk with chinese is most convenient.

the gdb info as follow:
(gdb) bt
#0  0x00007f5554c18796 in roseRunProgram_i (match_len=<optimized out>, prog_flags=<optimized out>, end=<optimized out>, som=<optimized out>,
    programOffset=<optimized out>, scratch=<optimized out>, t=<optimized out>)
    at /home/jenkins_workspace/SDK-corei7-avx/hyperscan-4.5.1/src/rose/program_runtime.h:1877
#1  roseRunProgram (t=<optimized out>, scratch=<optimized out>, programOffset=<optimized out>, som=<optimized out>, end=<optimized out>,
    match_len=<optimized out>, prog_flags=<optimized out>) at /home/jenkins_workspace/SDK-corei7-avx/hyperscan-4.5.1/src/rose/program_runtime.c:48
#2  0x00007f5554bf2f8e in roseAnchoredCallback (start=start@entry=0, end=<optimized out>, id=<optimized out>, ctx=<optimized out>)
    at /home/jenkins_workspace/SDK-corei7-avx/hyperscan-4.5.1/src/rose/match.c:219
#3  0x00007f5554babb5b in doComplexReport (cached_accept_id=<synthetic pointer>, cached_accept_state=<synthetic pointer>, eod=0 '\000', loc=5,
    s=10, m=0x83cf2540, ctxt=0x83cc8180, cb=0x7f5554bf2f10 <roseAnchoredCallback>)
    at /home/jenkins_workspace/SDK-corei7-avx/hyperscan-4.5.1/src/nfa/mcclellan.c:74
#4  mcclellanExec8_i (mode=CALLBACK_OUTPUT, c_final=0x0, single=0 '\000', ctxt=0x83cc8180, cb=0x7f5554bf2f10 <roseAnchoredCallback>, offAdj=0,
    len=5,
    buf=0x7f54e987f076 "POST /router/rest?sign=2520D80952DBA4D5042FD8D22D216A42&timestamp=2012-08-31+10%3A20%3A50&v=2.0&app_key=12349228&method=taobao.trade.fullinfo.get&sign_method=hmac&partner_id=top-sdk-java-20120817&sess"..., state=<synthetic pointer>, m=0x83cf2540)
    at /home/jenkins_workspace/SDK-corei7-avx/hyperscan-4.5.1/src/nfa/mcclellan.c:430
#5  nfaExecMcClellan8_Bi (single=0 '\000', context=0x83cc8180, cb=0x7f5554bf2f10 <roseAnchoredCallback>, length=5,
    buffer=0x7f54e987f076 "POST /router/rest?sign=2520D80952DBA4D5042FD8D22D216A42&timestamp=2012-08-31+10%3A20%3A50&v=2.0&app_key=12349228&method=taobao.trade.fullinfo.get&sign_method=hmac&partner_id=top-sdk-java-20120817&sess"..., offset=0, n=0x83cf2500)
    at /home/jenkins_workspace/SDK-corei7-avx/hyperscan-4.5.1/src/nfa/mcclellan.c:841
#6  nfaExecMcClellan8_B (n=0x83cf2500, offset=0,
    buffer=0x7f54e987f076 "POST /router/rest?sign=2520D80952DBA4D5042FD8D22D216A42&timestamp=2012-08-31+10%3A20%3A50&v=2.0&app_key=12349228&method=taobao.trade.fullinfo.get&sign_method=hmac&partner_id=top-sdk-java-20120817&sess"..., length=5, cb=0x7f5554bf2f10 <roseAnchoredCallback>,
    context=0x83cc8180) at /home/jenkins_workspace/SDK-corei7-avx/hyperscan-4.5.1/src/nfa/mcclellan.c:864
#7  0x00007f5554bdd4a4 in runAnchoredTableBlock (t=<optimized out>, scratch=0x83cc8180, atable=<optimized out>)
    at /home/jenkins_workspace/SDK-corei7-avx/hyperscan-4.5.1/src/rose/block.c:63
#8  roseBlockAnchored (scratch=0x83cc8180, t=0x83cf2200) at /home/jenkins_workspace/SDK-corei7-avx/hyperscan-4.5.1/src/rose/block.c:213
#9  roseBlockExec (t=<optimized out>, scratch=<optimized out>) at /home/jenkins_workspace/SDK-corei7-avx/hyperscan-4.5.1/src/rose/block.c:396
#10 0x00007f5554b2d8fe in rawBlockExec (scratch=0x83cc8180, rose=0x83cf2200)
    at /home/jenkins_workspace/SDK-corei7-avx/hyperscan-4.5.1/src/runtime.c:186
#11 hs_scan (db=<optimized out>, data=<optimized out>, length=488, flags=<optimized out>, scratch=0x83cc8180, onEvent=<optimized out>,
    userCtx=0x83cd0cc0) at /home/jenkins_workspace/SDK-corei7-avx/hyperscan-4.5.1/src/runtime.c:408
#12 0x00007f55551fb59d in matchTargetBlockMode (dbinfo=0x83cd0cc0,
    target=0x7f54e987f076 "POST /router/rest?sign=2520D80952DBA4D5042FD8D22D216A42&timestamp=2012-08-31+10%3A20%3A50&v=2.0&app_key=12349228&method=taobao.trade.fullinfo.get&sign_method=hmac&partner_id=top-sdk-java-20120817&sess"..., targetlen=488) at hyperscanwrap.cpp:536
#13 0x00007f55620b6e21 in regex_port_rule_match (coreid=<optimized out>, sport=<optimized out>, dport=<optimized out>,
    protoc=protoc@entry=6 '\006',
---Type <return> to continue, or q <return> to quit---
    payload=0x7f54e987f076 "POST /router/rest?sign=2520D80952DBA4D5042FD8D22D216A42&timestamp=2012-08-31+10%3A20%3A50&v=2.0&app_key=12349228&method=taobao.trade.fullinfo.get&sign_method=hmac&partner_id=top-sdk-java-20120817&sess"..., paylen=488, dbinfo=dbinfo@entry=0x7f54eaf94740)
    at rule_match.cpp:97

(gdb) p code
$8 = 250 '\372'
(gdb)

@cbuerger @argretzi @starius @EaseTheWorld  @jmtaylor90

**Comment by jviiret** [comment]
Hi,

This is unusual -- we shouldn't be seeing instruction codes outside the enum. These come from the Hyperscan bytecode, so to debug it further we would need a test case with a pattern (or set of patterns) and some input that triggers the issue. 

I will follow up via email with Xiang's contact details as well.

**Comment by jviiret** [comment]
After some discussion over email, this issue looks to be due to concurrent use of the same Hyperscan scratch region, which is not safe -- you need a separate scratch region for each concurrent scan call.

Closing for now; please do get in touch if you have further problems!

**Comment by landataosong** [comment]
Yes, it is my problem, Thanks for your help, Thanks!

2017-08-09 7:57 GMT+08:00 Justin Viiret <notifications@github.com>:
