### ISSUE TITLE
the relation hs_scratch_t and hs_database_t

### ISSUE THREAD

**Issue by david-holonet** [01org/hyperscan#66]
Hello, would you please explain the relation hs_scratch_t and hs_database_t?
Before hs_scan, we should create a database, and call `hs_alloc_scratch` to create scratch for every thread.

Here, my question is:
if **in one thread**, I have three databases, should I create three scratches? or can I share one scratch for all these databases?

Expect your answer, thanks!

**Comment by david-holonet** [comment]
I run block scan in hyperscan.

**Comment by mdb256** [comment]
The scratch space is a memory region for Hyperscan to store temporary information during a scan - it is used like the stack is in a process, but we can do the allocation ahead of time.

The `hs_database_t` object is read-only, so you can share databases between threads, but there must be a separate scratch per scanning context. A scanning context can be a thread, or recursive calls to Hyperscan from the match callback. There is more detail [in the documentation](http://01org.github.io/hyperscan/dev-reference/runtime.html#scratch-space).

If you are using multiple databases in one thread, then we recommend using a single scratch space by calling [`hs_alloc_scratch` with each database](http://01org.github.io/hyperscan/dev-reference/performance.html#allocate-one-scratch-space-per-scanning-context). This ensures that the scratch space is allocated appropriately for all of the databases.

**Comment by david-holonet** [comment]
OK, I got it. thanks!
